### ISSUE TITLE
Error when trying to fetch package with tarball deleted

### ISSUE THREAD

**Issue by stackdumper** [emeralt/emeralt#50]
### Error
```
➜ node build/index.js
Listening on 8080
PUT /@test%2fpackage-1 400 32.535 ms - 60
GET /@test%2fpackage-1 200 4.220 ms - 723
(node:75725) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pipe' of undefined
    at /Users/atamas1llya/Developer/emeralt/registry.emeralt.org/dev/registry/node_modules/@emeralt/server/build/index.js:238:8
    at Generator.next (<anonymous>)
    at fulfilled (/Users/atamas1llya/Developer/emeralt/registry.emeralt.org/dev/registry/node_modules/@emeralt/server/build/index.js:36:58)
(node:75725) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:75725) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
GET /-/tarball/%40test%2Fpackage-1/1.0.0 - - ms - -
```

**Comment by stackdumper** [comment]
Fixed in 6add886, will be available in `v0.7.0` ✨
